### ISSUE TITLE
[Feature]: Please release an update to `opentelemetry-aws` that depends on the the latest `opentelemetry`

### ISSUE THREAD

**Issue by dcormier** [open-telemetry/opentelemetry-rust-contrib#110]
### Describe the solution you'd like:

It would be nice to be able to use `opentelemetry-aws` with the latest version of `opentelemetry` (`0.25`). But `opentelemetry-aws` implements `opentelemetry::propagation::TextMapPropagator` from the previous version (`0.24`).

### Considered Alternatives

I've considered using a `[patch]` directive to use the code currently on github, but I'd rather use a released version.

**Comment by nakedible-p** [comment]
I can see a release is cooking from the commits, but please prioritize this. It's preventing updating opentelemetry in a number of places.

**Comment by cijothomas** [comment]
@lalitb is pushing releases to crates.io. (He was travelling, hence some delay!).

Also, we are looking for [someone to own the component](https://github.com/open-telemetry/opentelemetry-rust-contrib/issues/103#issuecomment-2330384053). Is that something you can take ownership of? We don't have a written set of policies yet to manage ownerships, but something we expect to have in the near future.

**Comment by nakedible-p** [comment]
Travel is an excellent excuse. Hopefully they had a nice trip!

I could consider ownership, but will need to think about it. At the moment this is very light on functionality, but there are many things that should be added.

**Comment by lalitb** [comment]
Some issue with the publishing (running `cargo publish`), 
```console
   Uploading opentelemetry-aws v0.13.0 (/tmp/opentelemetry-rust-contrib/opentelemetry-aws)
error: failed to publish to registry at https://crates.io

Caused by:
  the remote server responded with an error (status 403 Forbidden): this crate exists but you don't seem to be an owner. If you believe this is a mistake, perhaps you need to accept an invitation to be an owner before publishing.
```

Both me and @cijothomas are getting this error. 
@TommyCpp @hdost  Do you know what it could be? Could it be somwhat related to the recent accidental deletion of the OpenTelemetry Github team account?

**Comment by TommyCpp** [comment]
> Could it be somwhat related to the recent accidental deletion of the OpenTelemetry Github team account?

It could be. Maybe we try to remove the group from create.io and add it again?

**Comment by lalitb** [comment]
> It could be. Maybe we try to remove the group from create.io and add it again?

Yes tried that. It gives Internal Server Error (500) with that - https://github.com/rust-lang/crates.io/issues/9524

**Comment by nakedible-p** [comment]
@cijothomas Could I get some more info about the ways of working for maintaining the aws crate?

Alternatively, do you want to especially keep the create as part of opentelemetry-rust-contrib? Or could it make sense to just publish this separately? I'm open to multiple options.

**Comment by lalitb** [comment]
@open-telemetry/rust-maintainers  - based on the comment in https://github.com/rust-lang/crates.io/issues/9524, it seems we can't use this maintainer group name be used as crate owner. Should we raise a request in otel-community to rename it ?

**Comment by cijothomas** [comment]
> @cijothomas Could I get some more info about the ways of working for maintaining the aws crate?
> 
> Alternatively, do you want to especially keep the create as part of opentelemetry-rust-contrib? Or could it make sense to just publish this separately? I'm open to multiple options.

It is totally acceptable to keep the component in this repo. Contrib repo is generally the right place to host components that are outside of opentelemetry specification. Vendor specific components can be hosted here, assuming there is one(or more) person who can commit to maintaining (fixing bugs, responding to issues etc.) it. It maybe possible for AWS specific components be hosted by AWS itself.

**Comment by nakedible-p** [comment]
@cijothomas First to be clear, I'm in no way affiliated with AWS, I'm just a user of the component.

Secondly, my worry is that this repo has issues that relate to the wider set of contrib components here than just the AWS one. I fear that some general issue is going to prevent me from publishing a new version of "opentelemetry-aws", due to some totally unrelated stuff. It's not necessarily a blocker, but I'd sleep better if I know that when I "maintain" a component, I actually have control over it. So my question wasn't that is it fine to host it here, but my question is that is it fine to host it elsewhere.

**Comment by cijothomas** [comment]
> @cijothomas First to be clear, I'm in no way affiliated with AWS, I'm just a user of the component.
> 
> Secondly, my worry is that this repo has issues that relate to the wider set of contrib components here than just the AWS one. I fear that some general issue is going to prevent me from publishing a new version of "opentelemetry-aws", due to some totally unrelated stuff. It's not necessarily a blocker, but I'd sleep better if I know that when I "maintain" a component, I actually have control over it. So my question wasn't that is it fine to host it here, but my question is that is it fine to host it elsewhere.

Every component is independently managed, version and released. There should not be a scenario where one component affects another. If that occurs, it is on the maintainers of the repo to take care of that.

> when I "maintain" a component, I actually have control over it

You have reasonable amount of control. But ultimately, maintainers of this repo only can do the merge button press and do releases.

**Comment by cijothomas** [comment]
> So my question wasn't that is it fine to host it here, but my question is that is it fine to host it elsewhere.

We'll be posting an issue to invite owners for each component in this repo. Components without response in a reasonable amount of time will be removed from the repo, and anyone is free to take ownership here or take elsewhere. (there aren't many components now in this repo, so it is not yet a high priority to find and assign owners. But this is definitely something we plan to do in near future)
