### ISSUE TITLE
[Bug]: opentelemetry-datadog 0.13 is not compatible with opentelemetry 0.25

### ISSUE THREAD

**Issue by mcuelenaere** [open-telemetry/opentelemetry-rust-contrib#114]
### What happened?

As can be seen in https://github.com/open-telemetry/opentelemetry-rust-contrib/blob/main/opentelemetry-datadog/Cargo.toml#L30, `opentelemetry-datadog` is still on `0.24` instead of `0.25`, which results in build errors when trying to use them together.

### API Version

0.25

### SDK Version

0.25

### What component are you working with?

opentelemetry-datadog

**Comment by cijothomas** [comment]
Its broken and excluded from release now until https://github.com/open-telemetry/opentelemetry-rust-contrib/issues/67 is fixed
