### ISSUE TITLE
Add ETW Exporter for logs

### ISSUE THREAD

**Issue by cijothomas** [open-telemetry/opentelemetry-rust-contrib#15]
Opening an issue to track adding Exporters to ETW (Windows), similar to the user_events (Linux) exporter we have today.
https://github.com/open-telemetry/opentelemetry-rust-contrib/tree/main/opentelemetry-user-events-logs

**Comment by cijothomas** [comment]
@psandana has agreed to contribute this component!

**Comment by psandana** [comment]
> @psandana has agreed to contribute this component!

Yes! I will help with this one. Can you assign it to me?
