### ISSUE TITLE
[Bug]: `opentelemetry_aws` docs link to non-existent example

### ISSUE THREAD

**Issue by dcormier** [open-telemetry/opentelemetry-rust-contrib#18]
### What happened?

At the bottom of [the quick start section of the current docs](https://docs.rs/opentelemetry-aws/0.9.0/opentelemetry_aws/#quick-start) is a link titled "opentelemetry-rust", which points [here](https://github.com/open-telemetry/opentelemetry-rust/tree/main/examples/aws-xray) (404).

I haven't been able to find where this _should_ point.

### API Version

n/a

### SDK Version

n/a

### What component are you working with?

opentelemetry-aws

**Comment by cijothomas** [comment]
There is no example in this repo or the main repo. We can do either:
1. Simply remove the link.
2. Actually add an example under https://github.com/open-telemetry/opentelemetry-rust-contrib/tree/main/opentelemetry-aws, and make the link point to it.

By default, I am inclined to opt for 1, given the crate says it is [unofficial](https://github.com/open-telemetry/opentelemetry-rust-contrib/blob/main/opentelemetry-aws/src/lib.rs#L1), so not sure who can do 2!

If there is an owner to help contribute an example, we can do 2.

**Comment by cijothomas** [comment]
https://docs.rs/opentelemetry-aws/0.10.0/opentelemetry_aws/ Closing, as there are no dead links anymore.

**Comment by dcormier** [comment]
The broken link are still visible in the latest docs. It's [over here](https://docs.rs/opentelemetry-aws/0.10.0/opentelemetry_aws/trace/xray_propagator/index.html#quick-start), now, @cijothomas

**Comment by cijothomas** [comment]
Oops! Reopened.
