### ISSUE TITLE
Add Google Trace propagator

### ISSUE THREAD

**Issue by lucacasonato** [open-telemetry/opentelemetry-rust-contrib#3]
Should this be added to `opentelemetry` or `opentelemetry-contrib`? Unless anyone else wants to implement this, I will do it.

Go implementation for opencensus: https://github.com/census-instrumentation/opencensus-go/blob/v0.22.5/exporter/stackdriver/propagation/http.go

**Comment by cijothomas** [comment]
Closed via https://github.com/open-telemetry/opentelemetry-rust-contrib/pull/25
