### ISSUE TITLE
[Feature]: BinaryFormat::deserialize_from_bytes should take a byte-slice, not a Vec<u8>

### ISSUE THREAD

**Issue by Alxandr** [open-telemetry/opentelemetry-rust-contrib#31]
### Describe the solution you'd like:

The method should take a byte-slice (`&[u8]`) instead.

### Additional Context

Having `BinaryFormat::deserialize_from_bytes` take a `Vec<u8>` requires allocating a separate vec, copying data to it, calling the function only for it then to drop the vec again.

**Comment by lalitb** [comment]
@Alxandr This is a valid optimization. Would you like to contribute, can assign it to you in that case?

**Comment by Alxandr** [comment]
I can do that :)
