### ISSUE TITLE
[Feature]: Config user_events name via exporter config instead of ReentrantLogProcessor in user_events logs exporter

### ISSUE THREAD

**Issue by ThomsonTan** [open-telemetry/opentelemetry-rust-contrib#80]
### Describe the solution you'd like:

Currently the name of the user_events provider is configured by ReentrantLogProcessor, ideally it should be an option in the `ExporterConfig` so it doesn't rely on any processor.

https://github.com/open-telemetry/opentelemetry-rust-contrib/blob/main/opentelemetry-user-events-logs/examples/basic-logs.rs#L15

**Comment by cijothomas** [comment]
covered via https://github.com/open-telemetry/opentelemetry-rust-contrib/pull/82
