### ISSUE TITLE
Update opentelemetry-datadog to Otel v0.24

### ISSUE THREAD

**Issue by lalitb** [open-telemetry/opentelemetry-rust-contrib#87]
### What happened?

**Update opentelemetry-datadog to Otel v0.24**

### API Version

0.24

### SDK Version

0.24

### Relevant log output

```shell
N/A
```

**Comment by StevenPenn** [comment]
Will try to work on this issue.

**Comment by StevenPenn** [comment]
I noticed that the OTEL version of DataDog is upgraded. This issue can be closed now.
https://github.com/open-telemetry/opentelemetry-rust-contrib/blob/main/opentelemetry-datadog/Cargo.toml#L30

**Comment by lalitb** [comment]
Yes, this was done with #97. It seems the otel and otel-sdk versions are not being picked from the workspace. I will get it fixed in the next release.
